<? 
//|||||||||||||||configuração de cores||||||||||||||||||||||||
	
	//cores do texto das linhas pares
	$cortexto1="#996699";
	//cores do texto das linhas ímpares
	$cortexto2="#0033cc";
	//cores das  linhas pares
	$corlinha1="#ccffff";
	//cores  das linhas ímpares
	$corlinha2="#dbdbdb";
	//cor das linhas em destaque	
	$corlinha3="#ffffcc";
	//Ano do carro a ser destacado
	$limite="2000";
	//cor da linha dos títulos
	$caption="#ccccff";
	//cor do texto da linha dos títulos
	$cortitulo="brown";
	//Definindo negrito ou não para os títulos
	//bold ou normal
	$negrito="bold";
	//cor da borda
	$cor_borda="gray";
	//estilo da borda
	//groove - solid - inset - outset - double - ridge - none
    $estilo="solid";
	//tamanho da borda da célula
	$borda_celula=1;
	//tamanho da borda da tabela
	$borda_tabela=2;
	
//||||||||||||fim configuração de cores|||||||||||||||||||||||||
?>
